// <auto-generated />
using System;
using ITC.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITC_BE.Migrations
{
    [DbContext(typeof(ITCDBContext))]
    partial class ITCDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ITC.Data.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ITC.Data.Entities.CoursePlans", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Activity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contents")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkillName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CoursePlans");
                });

            modelBuilder.Entity("ITC.Data.Entities.EmpTasks", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TaskName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("EmpTasks");
                });

            modelBuilder.Entity("ITC.Data.Entities.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CoursePlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CoursePlansId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ScoresId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TotalPoint")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CoursePlansId");

                    b.HasIndex("ScoresId");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("ITC.Data.Entities.Images", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RevId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SchooldId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SchoolsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SchooldId");

                    b.HasIndex("SchoolsId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("ITC.Data.Entities.LessonPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SchoolsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SubId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SchoolsId");

                    b.HasIndex("SubId");

                    b.ToTable("LessonPlans");
                });

            modelBuilder.Entity("ITC.Data.Entities.PartnersInformation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Features")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartnerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("PartnersInformations");
                });

            modelBuilder.Entity("ITC.Data.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BankAccountBeneficiary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankAccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankBranch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SchoolsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SwiftCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SchoolsId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("ITC.Data.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CoursePlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CoursePlansId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Introduction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Leader")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localtion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MountOfTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("MyProperty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SubId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("TotalStaff")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalStudent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CoursePlansId");

                    b.HasIndex("SubId");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("ITC.Data.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Information")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostDay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("ITC.Data.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ITC.Data.Entities.RoleUser", b =>
                {
                    b.Property<Guid>("RoleUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RolesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleUserId");

                    b.HasIndex("RolesId");

                    b.HasIndex("UsersId");

                    b.ToTable("RoleUsers");
                });

            modelBuilder.Entity("ITC.Data.Entities.Schools", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SchoolName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("ITC.Data.Entities.Score", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Minimumpass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Percent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("ITC.Data.Entities.StudentInformation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageBillTuitionFee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePassport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PercentAccept")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StatusTuitionFee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SubCategoriesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.HasIndex("SubCategoriesId");

                    b.ToTable("StudentInformations");
                });

            modelBuilder.Entity("ITC.Data.Entities.SubCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoriesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriesId");

                    b.ToTable("SubCategories");
                });

            modelBuilder.Entity("ITC.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StudentInformationsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("StudentInformationsId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ITC.Data.Entities.EmpTasks", b =>
                {
                    b.HasOne("ITC.Data.Entities.Project", "Project")
                        .WithMany("EmpTasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ITC.Data.Entities.Exam", b =>
                {
                    b.HasOne("ITC.Data.Entities.CoursePlans", "CoursePlans")
                        .WithMany("Exams")
                        .HasForeignKey("CoursePlansId");

                    b.HasOne("ITC.Data.Entities.Score", "Scores")
                        .WithMany("Exams")
                        .HasForeignKey("ScoresId");

                    b.HasOne("ITC.Data.Entities.StudentInformation", "Students")
                        .WithOne("Exams")
                        .HasForeignKey("ITC.Data.Entities.Exam", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoursePlans");

                    b.Navigation("Scores");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("ITC.Data.Entities.Images", b =>
                {
                    b.HasOne("ITC.Data.Entities.Review", "Reviews")
                        .WithMany("Images")
                        .HasForeignKey("SchooldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITC.Data.Entities.Schools", "Schools")
                        .WithMany("Images")
                        .HasForeignKey("SchoolsId");

                    b.Navigation("Reviews");

                    b.Navigation("Schools");
                });

            modelBuilder.Entity("ITC.Data.Entities.LessonPlan", b =>
                {
                    b.HasOne("ITC.Data.Entities.Schools", "Schools")
                        .WithMany("LessonPlans")
                        .HasForeignKey("SchoolsId");

                    b.HasOne("ITC.Data.Entities.SubCategory", "SubCategories")
                        .WithMany("LessonPlans")
                        .HasForeignKey("SubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schools");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("ITC.Data.Entities.PartnersInformation", b =>
                {
                    b.HasOne("ITC.Data.Entities.Project", "Projects")
                        .WithMany("PartnersInformations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("ITC.Data.Entities.Payment", b =>
                {
                    b.HasOne("ITC.Data.Entities.Schools", null)
                        .WithMany("Payments")
                        .HasForeignKey("SchoolsId");
                });

            modelBuilder.Entity("ITC.Data.Entities.Project", b =>
                {
                    b.HasOne("ITC.Data.Entities.CoursePlans", "CoursePlans")
                        .WithMany("Projects")
                        .HasForeignKey("CoursePlansId");

                    b.HasOne("ITC.Data.Entities.SubCategory", "SubCategories")
                        .WithMany("Projects")
                        .HasForeignKey("SubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoursePlans");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("ITC.Data.Entities.RoleUser", b =>
                {
                    b.HasOne("ITC.Data.Entities.Role", "Roles")
                        .WithMany("RoleUsers")
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITC.Data.Entities.User", "Users")
                        .WithMany("RoleUsers")
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ITC.Data.Entities.Schools", b =>
                {
                    b.HasOne("ITC.Data.Entities.Project", "Projects")
                        .WithMany("Schools")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("ITC.Data.Entities.StudentInformation", b =>
                {
                    b.HasOne("ITC.Data.Entities.Schools", "Schools")
                        .WithMany("StudentInformations")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITC.Data.Entities.SubCategory", "SubCategories")
                        .WithMany("StudentInformations")
                        .HasForeignKey("SubCategoriesId");

                    b.Navigation("Schools");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("ITC.Data.Entities.SubCategory", b =>
                {
                    b.HasOne("ITC.Data.Entities.Category", "Categories")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoriesId");

                    b.Navigation("Categories");
                });

            modelBuilder.Entity("ITC.Data.Entities.User", b =>
                {
                    b.HasOne("ITC.Data.Entities.SubCategory", "SubCategories")
                        .WithMany("Users")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITC.Data.Entities.StudentInformation", "StudentInformations")
                        .WithMany("Users")
                        .HasForeignKey("StudentInformationsId");

                    b.Navigation("StudentInformations");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("ITC.Data.Entities.Category", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("ITC.Data.Entities.CoursePlans", b =>
                {
                    b.Navigation("Exams");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("ITC.Data.Entities.Project", b =>
                {
                    b.Navigation("EmpTasks");

                    b.Navigation("PartnersInformations");

                    b.Navigation("Schools");
                });

            modelBuilder.Entity("ITC.Data.Entities.Review", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("ITC.Data.Entities.Role", b =>
                {
                    b.Navigation("RoleUsers");
                });

            modelBuilder.Entity("ITC.Data.Entities.Schools", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("LessonPlans");

                    b.Navigation("Payments");

                    b.Navigation("StudentInformations");
                });

            modelBuilder.Entity("ITC.Data.Entities.Score", b =>
                {
                    b.Navigation("Exams");
                });

            modelBuilder.Entity("ITC.Data.Entities.StudentInformation", b =>
                {
                    b.Navigation("Exams");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ITC.Data.Entities.SubCategory", b =>
                {
                    b.Navigation("LessonPlans");

                    b.Navigation("Projects");

                    b.Navigation("StudentInformations");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ITC.Data.Entities.User", b =>
                {
                    b.Navigation("RoleUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
